# Generated by Django 5.2.10 on 2026-02-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventschema",
            options={},
        ),
        migrations.RenameIndex(
            model_name="contractevent",
            new_name="ingest_cont_contrac_07c066_idx",
            old_name="ingest_cont_contract_7f8c2a_idx",
        ),
        migrations.RenameIndex(
            model_name="contractevent",
            new_name="ingest_cont_ledger_dde0a1_idx",
            old_name="ingest_cont_ledger_2a1b3c_idx",
        ),
        migrations.RenameIndex(
            model_name="contractevent",
            new_name="ingest_cont_tx_hash_24128c_idx",
            old_name="ingest_cont_tx_hash_4d5e6f_idx",
        ),
        migrations.RenameIndex(
            model_name="trackedcontract",
            new_name="ingest_trac_contrac_7989b1_idx",
            old_name="ingest_trac_contrac_9b2b0d_idx",
        ),
        migrations.AddField(
            model_name="contractevent",
            name="event_index",
            field=models.PositiveIntegerField(
                default=0, help_text="0-based event index within the ledger"
            ),
        ),
        migrations.AddField(
            model_name="trackedcontract",
            name="last_indexed_ledger",
            field=models.PositiveBigIntegerField(
                blank=True,
                db_index=True,
                help_text="Last ledger sequence that was indexed for this contract",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="contractevent",
            index=models.Index(
                fields=["contract", "ledger", "event_index"],
                name="ingest_cont_contrac_c5f862_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractevent",
            constraint=models.UniqueConstraint(
                fields=("contract", "ledger", "event_index"),
                name="unique_contract_ledger_event_index",
            ),
        ),
    ]
