# Generated by Django to merge conflicting migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0024_merge_20260328_1903"),
        ("ingest", "0025_merge_final_conflicts"),
    ]

    operations = []
